In [1]:
pip install pandas

In [6]:
pip install sklearn

  Using cached sklearn-0.0.post5.tar.gz (3.7 kB)
  Preparing metadata (setup.py) ... done
  Created wheel for sklearn: filename=sklearn-0.0.post5-py3-none-any.whl size=2950 sha256=87ae6eb0b019de0ab1b84dda9ab113a84240098c82dacfa356e5f99b92d5297d
  Stored in directory: /root/.cache/pip/wheels/38/1f/8d/4f812c590e074c1e928f5cec67bf5053b71f38e2648739403a
Successfully built sklearn


In [7]:
import pandas as pd
import numpy as np

In [9]:
sms_data = pd.read_csv("/content/drive/MyDrive/NLP Practicals/spam.csv", encoding='latin-1')

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [10]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [11]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [12]:
stemming = PorterStemmer()
corpus = []
for i in range (0,len(sms_data)):
  s1 = re.sub('[^a-zA-Z]',repl = ' ',string = sms_data['v2'][i])
  s1.lower()
  s1 = s1.split()
  s1 = [stemming.stem(word) for word in s1 if word not in
        set(stopwords.words('english'))]
  s1 = ' '.join(s1)
  corpus.append(s1)

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
countvectorizer =CountVectorizer()

In [14]:
x = countvectorizer.fit_transform(corpus).toarray()
print(x)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [15]:
y = sms_data['v1'].values
print(y)

['ham' 'ham' 'spam' ... 'ham' 'ham' 'ham']


In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,
stratify=y,random_state=2)

In [17]:
#Multinomial Naïve Bayes.
from sklearn.naive_bayes import MultinomialNB
multinomialnb = MultinomialNB()
multinomialnb.fit(x_train,y_train)

MultinomialNB()

In [18]:
# Predicting on test data:
y_pred = multinomialnb.predict(x_test)
print(y_pred)

['ham' 'ham' 'ham' ... 'ham' 'ham' 'ham']


In [19]:
#Results of our Models
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score

In [20]:
print(classification_report(y_test,y_pred))
print("accuracy_score: ",accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

         ham       0.99      0.99      0.99      1448
        spam       0.92      0.93      0.92       224

    accuracy                           0.98      1672
   macro avg       0.95      0.96      0.96      1672
weighted avg       0.98      0.98      0.98      1672

accuracy_score:  0.979066985645933
